export const foodItems = [
  {
    id: 1,
    name: "Hyderabadi Dum Biryani",
    category: "Biryani",
    price: 350,
    rating: 4.8,
    reviews: 1240,
    time: "30-40 min",
    image: "/images/biryani_1786102325140.jpg",
    description: "Authentic Indian biryani with aromatic saffron rice, tender meat, and rich spices.",
    isVeg: false
  },
  {
    id: 2,
    name: "Classic Cheese Pizza",
    category: "Pizza",
    price: 450,
    rating: 4.6,
    reviews: 854,
    time: "25-35 min",
    image: "/images/pizza_1786102363129.jpg",
    description: "Traditional Italian pizza topped with fresh tomatoes, basil, and melting mozzarella.",
    isVeg: true
  },
  {
    id: 3,
    name: "Spicy Stir-Fried Noodles",
    category: "Noodles",
    price: 220,
    rating: 4.5,
    reviews: 532,
    time: "20-30 min",
    image: "/images/noodles_1786102348703.jpg",
    description: "Delicious wok-tossed noodles with fresh vegetables and a spicy, savory sauce.",
    isVeg: true
  },
  {
    id: 4,
    name: "Gourmet Beef Burger",
    category: "Burger",
    price: 280,
    rating: 4.9,
    reviews: 2100,
    time: "15-25 min",
    image: "/images/burger_1786102375077.jpg",
    description: "Juicy beef patty with fresh lettuce, ripe tomatoes, and cheddar on a toasted sesame bun.",
    isVeg: false
  },
  {
    id: 5,
    name: "Fresh Tropical Juice",
    category: "Drinks",
    price: 120,
    rating: 4.7,
    reviews: 320,
    time: "10-15 min",
    image: "/images/fresh_juice_1786102336871.jpg",
    description: "A refreshing blend of seasonal tropical fruits, served ice-cold.",
    isVeg: true
  },
  {
    id: 6,
    name: "Chicken Tikka Biryani",
    category: "Biryani",
    price: 380,
    rating: 4.7,
    reviews: 940,
    time: "35-45 min",
    image: "/images/biryani_1786102325140.jpg",
    description: "Smoky chicken tikka layered with fragrant basmati rice and secret spices.",
    isVeg: false
  },
  {
    id: 7,
    name: "Pepperoni Feast Pizza",
    category: "Pizza",
    price: 550,
    rating: 4.8,
    reviews: 1120,
    time: "30-40 min",
    image: "/images/pizza_1786102363129.jpg",
    description: "Loaded with crispy pepperoni slices and extra cheese on our signature crust.",
    isVeg: false
  },
  {
    id: 8,
    name: "Crispy Chicken Burger",
    category: "Burger",
    price: 250,
    rating: 4.6,
    reviews: 890,
    time: "15-25 min",
    image: "/images/burger_1786102375077.jpg",
    description: "Crispy fried chicken breast, spicy mayo, and pickles in a brioche bun.",
    isVeg: false
  },
  {
    id: 9,
    name: "Mutton Keema Biryani",
    category: "Biryani",
    price: 420,
    rating: 4.9,
    reviews: 750,
    time: "35-45 min",
    image: "/images/biryani_1786102325140.jpg",
    description: "Rich minced mutton cooked with basmati rice and royal awadhi spices.",
    isVeg: false
  },
  {
    id: 10,
    name: "Veg Supreme Pizza",
    category: "Pizza",
    price: 390,
    rating: 4.5,
    reviews: 620,
    time: "25-35 min",
    image: "/images/pizza_1786102363129.jpg",
    description: "Loaded with black olives, capsicum, onion, mushroom, and golden corn.",
    isVeg: true
  },
  {
    id: 11,
    name: "Hakka Noodles",
    category: "Noodles",
    price: 180,
    rating: 4.4,
    reviews: 450,
    time: "15-20 min",
    image: "/images/noodles_1786102348703.jpg",
    description: "Classic Indo-Chinese style noodles tossed with shredded veggies and soy sauce.",
    isVeg: true
  },
  {
    id: 12,
    name: "Double Cheese Burger",
    category: "Burger",
    price: 320,
    rating: 4.8,
    reviews: 1340,
    time: "15-25 min",
    image: "/images/burger_1786102375077.jpg",
    description: "Two juicy patties with double layers of melting cheese and our special sauce.",
    isVeg: false
  },
  {
    id: 13,
    name: "Watermelon Mint Juice",
    category: "Drinks",
    price: 110,
    rating: 4.6,
    reviews: 280,
    time: "5-10 min",
    image: "/images/fresh_juice_1786102336871.jpg",
    description: "Chilled fresh watermelon juice with a hint of mint leaves.",
    isVeg: true
  },
  {
    id: 14,
    name: "Paneer Tikka Pizza",
    category: "Pizza",
    price: 420,
    rating: 4.7,
    reviews: 580,
    time: "25-35 min",
    image: "/images/pizza_1786102363129.jpg",
    description: "Tandoori paneer, red paprika, and capsicum on a crispy crust.",
    isVeg: true
  },
  {
    id: 15,
    name: "Egg Fried Noodles",
    category: "Noodles",
    price: 190,
    rating: 4.5,
    reviews: 340,
    time: "15-20 min",
    image: "/images/noodles_1786102348703.jpg",
    description: "Wok-tossed noodles with scrambled egg, spring onions, and light soy sauce.",
    isVeg: false
  },
  {
    id: 16,
    name: "Veg Dum Biryani",
    category: "Biryani",
    price: 280,
    rating: 4.6,
    reviews: 820,
    time: "30-40 min",
    image: "/images/biryani_1786102325140.jpg",
    description: "Aromatic basmati rice cooked with mixed vegetables and rich spices.",
    isVeg: true
  },
  {
    id: 17,
    name: "Chicken Schezwan Noodles",
    category: "Noodles",
    price: 260,
    rating: 4.7,
    reviews: 670,
    time: "20-30 min",
    image: "/images/noodles_1786102348703.jpg",
    description: "Spicy Schezwan noodles with tender chicken chunks and veggies.",
    isVeg: false
  },
  {
    id: 18,
    name: "Aloo Tikki Burger",
    category: "Burger",
    price: 150,
    rating: 4.3,
    reviews: 1500,
    time: "10-20 min",
    image: "/images/burger_1786102375077.jpg",
    description: "Crispy potato patty with fresh onions, tomatoes, and creamy mayo.",
    isVeg: true
  },
  {
    id: 19,
    name: "Orange Mint Cooler",
    category: "Drinks",
    price: 130,
    rating: 4.8,
    reviews: 410,
    time: "5-10 min",
    image: "/images/fresh_juice_1786102336871.jpg",
    description: "Freshly squeezed orange juice blended with crushed mint and ice.",
    isVeg: true
  },
  {
    id: 20,
    name: "BBQ Chicken Pizza",
    category: "Pizza",
    price: 490,
    rating: 4.8,
    reviews: 1250,
    time: "30-40 min",
    image: "/images/pizza_1786102363129.jpg",
    description: "Smoky BBQ chicken, red onions, and mozzarella on a hand-tossed base.",
    isVeg: false
  }
];

export const categories = ["All", "Biryani", "Pizza", "Noodles", "Burger", "Drinks"];
